"""Plan-Execute pattern - plan first, then execute steps sequentially."""

from __future__ import annotations

import json
import re
import time
import uuid
from typing import Any, AsyncIterator

from pydantic import BaseModel

from synapse_core.agent import AgentDefinition
from synapse_core.llm import LLMConfig, LLMMessage
from synapse_core.llm.providers import create_provider
from synapse_core.streaming import (
    StreamEvent,
    run_start,
    run_end,
    agent_think,
    agent_message,
    run_error,
)
from synapse_core.tools import ToolRegistry
from synapse_core.graph import GraphBuilder
from synapse_core.graph.state import TokenUsage
from synapse_core.observability import get_hub


class PlanStep(BaseModel):
    """A single step in the execution plan."""

    step_number: int
    description: str
    tool_hint: str = ""
    status: str = "pending"  # pending | running | completed | failed | skipped


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by the planner."""

    goal: str
    steps: list[PlanStep]
    reasoning: str = ""


class PlanExecutePattern:
    """
    Plan-Execute pattern: LLM first generates a complete plan,
    then each step is executed sequentially. Supports replanning
    when a step fails or produces unexpected results.

    Advantages over ReAct:
    - Lower token consumption (one planning call vs many think-act cycles)
    - Better control over execution flow
    - Clearer progress tracking
    - Suitable for complex, multi-step tasks
    """

    def __init__(
        self,
        planner: AgentDefinition,
        executor: AgentDefinition | None = None,
        tool_registry: ToolRegistry | None = None,
        max_replans: int = 2,
        enable_replan: bool = True,
    ) -> None:
        self.planner = planner
        self.executor = executor or planner
        self.tool_registry = tool_registry
        self.max_replans = max_replans
        self.enable_replan = enable_replan
        self._planner_provider = create_provider(planner.llm)

    def _build_planning_prompt(self, task: str) -> str:
        tools_desc = ""
        if self.tool_registry:
            available = self.tool_registry.list_all()
            if available:
                tools_desc = "\n\nAvailable tools:\n" + "\n".join(
                    f"- {t.name}: {t.description}" for t in available
                )

        return f"""You are {self.planner.name}, a task planner. {self.planner.role}
Goal: {self.planner.goal}

Create a step-by-step execution plan for the following task:
{task}
{tools_desc}

Rules:
- Break the task into 2-8 concrete steps
- Each step should be a single, clear action
- If a step needs a tool, mention which one
- Order steps logically (dependencies first)

Respond with a JSON object:
{{
  "reasoning": "<brief analysis of the task>",
  "steps": [
    {{"step_number": 1, "description": "<what to do>", "tool_hint": "<tool name or empty>"}},
    {{"step_number": 2, "description": "<what to do>", "tool_hint": "<tool name or empty>"}}
  ]
}}

Only output valid JSON, no additional text."""

    def _build_replan_prompt(
        self,
        original_task: str,
        plan: ExecutionPlan,
        completed_steps: list[dict[str, Any]],
        failed_step: PlanStep | None,
        failure_reason: str = "",
    ) -> str:
        completed_desc = "\n".join(
            f"  Step {s['step']}: {s['result'][:200]}" for s in completed_steps
        )
        failed_desc = ""
        if failed_step:
            failed_desc = f"\nFailed step {failed_step.step_number}: {failed_step.description}\nFailure reason: {failure_reason}"

        return f"""You are {self.planner.name}, a task planner. The original plan needs adjustment.

Original task: {original_task}

Completed steps:
{completed_desc}
{failed_desc}

Generate an updated plan for the remaining work. You may:
- Adjust remaining steps based on completed results
- Add new steps if needed
- Skip steps that are no longer necessary

Respond with a JSON object:
{{
  "reasoning": "<why the replan is needed>",
  "steps": [
    {{"step_number": 1, "description": "<what to do>", "tool_hint": "<tool name or empty>"}}
  ]
}}

Only output valid JSON, no additional text."""

    def _parse_plan(self, content: str) -> ExecutionPlan | None:
        """Parse LLM response into an ExecutionPlan."""
        # Try direct JSON parse
        try:
            data = json.loads(content)
            return ExecutionPlan(
                goal="",
                steps=[
                    PlanStep(
                        step_number=s.get("step_number", i + 1),
                        description=s.get("description", ""),
                        tool_hint=s.get("tool_hint", ""),
                    )
                    for i, s in enumerate(data.get("steps", []))
                ],
                reasoning=data.get("reasoning", ""),
            )
        except (json.JSONDecodeError, KeyError):
            pass

        # Try extracting JSON from markdown code block
        json_match = re.search(r"```(?:json)?\s*\n?(.*?)```", content, re.DOTALL)
        if json_match:
            try:
                data = json.loads(json_match.group(1).strip())
                return ExecutionPlan(
                    goal="",
                    steps=[
                        PlanStep(
                            step_number=s.get("step_number", i + 1),
                            description=s.get("description", ""),
                            tool_hint=s.get("tool_hint", ""),
                        )
                        for i, s in enumerate(data.get("steps", []))
                    ],
                    reasoning=data.get("reasoning", ""),
                )
            except (json.JSONDecodeError, KeyError):
                pass

        return None

    async def run(self, task: str, run_id: str | None = None) -> AsyncIterator[StreamEvent]:
        run_id = run_id or str(uuid.uuid4())
        start_time = time.monotonic()
        total_usage = TokenUsage()
        hub = get_hub()

        yield run_start(run_id, self.planner.id)

        try:
            # Phase 1: Planning
            yield agent_think(self.planner.id, "Generating execution plan...")

            plan_messages = [
                LLMMessage(role="system", content=self._build_planning_prompt(task)),
                LLMMessage(role="user", content=task),
            ]

            t0 = time.monotonic()
            plan_response = await self._planner_provider.invoke(plan_messages)
            plan_duration = (time.monotonic() - t0) * 1000
            if plan_response.usage:
                u = plan_response.usage
                total_usage = total_usage.add(TokenUsage(**u))
                hub.track_llm_call(
                    provider=self.planner.llm.provider,
                    model=plan_response.model or self.planner.llm.model,
                    tokens_in=u.get("prompt_tokens", 0),
                    tokens_out=u.get("completion_tokens", 0),
                    duration_ms=plan_duration,
                )

            plan = self._parse_plan(plan_response.content)
            if not plan or not plan.steps:
                yield agent_message(
                    self.planner.id,
                    "Unable to generate a valid plan. Let me answer directly.\n\n"
                    + plan_response.content,
                )
                duration = (time.monotonic() - start_time) * 1000
                yield run_end(run_id, total_usage.model_dump(), duration)
                return

            plan.goal = task
            yield agent_think(
                self.planner.id,
                f"Plan created: {len(plan.steps)} steps. {plan.reasoning}",
            )

            # Phase 2: Execution
            replan_count = 0
            completed_results: list[dict[str, Any]] = []

            while True:
                all_done = True
                for step in plan.steps:
                    if step.status in ("completed", "skipped"):
                        continue
                    all_done = False

                    step.status = "running"
                    yield agent_think(
                        self.planner.id,
                        f"Executing step {step.step_number}/{len(plan.steps)}: {step.description}",
                    )

                    # Execute step using executor agent
                    step_task = self._build_step_task(step, completed_results)

                    if self.tool_registry:
                        builder = GraphBuilder(self.executor, self.tool_registry)
                        step_result = ""
                        async for event in builder.run(step_task, f"{run_id}-s{step.step_number}"):
                            yield event
                            if event.type == "agent:message":
                                step_result = event.data.get("content", "")
                            if event.type == "run:end":
                                wu = event.data.get("tokenUsage", event.data.get("token_usage", {}))
                                if wu:
                                    total_usage = total_usage.add(TokenUsage(
                                        prompt_tokens=wu.get("prompt_tokens", 0),
                                        completion_tokens=wu.get("completion_tokens", 0),
                                        total_tokens=wu.get("total_tokens", 0),
                                    ))
                    else:
                        # No tools: direct LLM call
                        executor_provider = create_provider(self.executor.llm)
                        step_messages = [
                            LLMMessage(role="system", content=self._build_executor_prompt()),
                            LLMMessage(role="user", content=step_task),
                        ]
                        t1 = time.monotonic()
                        resp = await executor_provider.invoke(step_messages)
                        call_dur = (time.monotonic() - t1) * 1000
                        if resp.usage:
                            u = resp.usage
                            total_usage = total_usage.add(TokenUsage(**u))
                            hub.track_llm_call(
                                provider=self.executor.llm.provider,
                                model=resp.model or self.executor.llm.model,
                                tokens_in=u.get("prompt_tokens", 0),
                                tokens_out=u.get("completion_tokens", 0),
                                duration_ms=call_dur,
                            )
                        step_result = resp.content
                        yield agent_message(self.executor.id, step_result)

                    if step_result:
                        step.status = "completed"
                        completed_results.append({
                            "step": step.step_number,
                            "description": step.description,
                            "result": step_result,
                        })
                    else:
                        step.status = "failed"
                        # Try replanning
                        if self.enable_replan and replan_count < self.max_replans:
                            replan_count += 1
                            yield agent_think(
                                self.planner.id,
                                f"Step {step.step_number} failed. Replanning ({replan_count}/{self.max_replans})...",
                            )
                            new_plan = await self._replan(
                                task, plan, completed_results, step
                            )
                            if new_plan:
                                plan = new_plan
                                break  # Restart the execution loop with new plan
                        else:
                            completed_results.append({
                                "step": step.step_number,
                                "description": step.description,
                                "result": f"[FAILED] Step could not be completed.",
                            })

                if all_done:
                    break

            # Phase 3: Final summary
            yield agent_think(self.planner.id, "All steps completed. Generating summary.")
            summary = self._build_summary(plan, completed_results)
            yield agent_message(self.planner.id, summary)

            duration = (time.monotonic() - start_time) * 1000
            yield run_end(run_id, total_usage.model_dump(), duration)

        except Exception as e:
            yield run_error(run_id, str(e), recoverable=True)

    async def _replan(
        self,
        original_task: str,
        current_plan: ExecutionPlan,
        completed_steps: list[dict[str, Any]],
        failed_step: PlanStep,
    ) -> ExecutionPlan | None:
        """Generate a new plan based on completed results and failure."""
        replan_messages = [
            LLMMessage(
                role="system",
                content=self._build_replan_prompt(
                    original_task, current_plan, completed_steps, failed_step
                ),
            ),
        ]
        response = await self._planner_provider.invoke(replan_messages)
        return self._parse_plan(response.content)

    def _build_step_task(self, step: PlanStep, previous_results: list[dict[str, Any]]) -> str:
        context = ""
        if previous_results:
            context = "\n\nPrevious results:\n" + "\n".join(
                f"- Step {r['step']}: {r['result'][:300]}" for r in previous_results[-3:]
            )
        return f"Execute the following step: {step.description}{context}"

    def _build_executor_prompt(self) -> str:
        return f"""You are {self.executor.name}, {self.executor.role}.
Goal: {self.executor.goal}
Execute the given step precisely and return the result."""

    def _build_summary(self, plan: ExecutionPlan, results: list[dict[str, Any]]) -> str:
        lines = [f"**Execution Plan: {plan.goal}**\n"]
        lines.append(f"Reasoning: {plan.reasoning}\n")
        lines.append("**Steps:**")
        for step in plan.steps:
            status_icon = {"completed": "[OK]", "failed": "[FAIL]", "skipped": "[SKIP]", "pending": "[PEND]", "running": "[RUN]"}
            icon = status_icon.get(step.status, "[?]")
            result_text = ""
            for r in results:
                if r["step"] == step.step_number:
                    result_text = f" -> {r['result'][:150]}"
            lines.append(f"  {icon} Step {step.step_number}: {step.description}{result_text}")
        return "\n".join(lines)
